### ISSUE TITLE
Multiple jooq code-gen configurations

### ISSUE THREAD

**Issue by eikek** [kxbmap/sbt-jooq#10]
Hi,
I have another question: I want to generate jooq code from multiple databases in one project. Afaik, jooq code generation can only be run with one database connection (given in the xml file). It would be nice to specify multiple such xml files. Currently I use different submodules, one per jooq xml file. 
I first thought it would be easy to add, but I didn't see that you can specify more than just the xml file (`RewriteRule` and literal xml config) – so I'm unsure how to do this. 
Do you know a way how to apply the plugin multiple times (so no code change is necessary)? Or do you think it is possible to add without much hassle?
Thank in advance!

**Comment by kxbmap** [comment]
> Do you know a way how to apply the plugin multiple times (so no code change is necessary)? 

No, I don't know.

> Or do you think it is possible to add without much hassle?

I have not come up with a way to do it well.
Maybe significant change will be required.

For now it's better to use submodules  as you are doing.

**Comment by kxbmap** [comment]
sbt-jooq version 0.3.3 released.

Now you can run jooq-codegen with any config file:
`sbt> jooq:run config1.xml config2.xml`

Also override several tasks, you can get automatically code generation with multiple configurations.
Here is the example project:
https://github.com/kxbmap/sbt-jooq/tree/v0.3.3/src/sbt-test/sbt-jooq/multidb

**Comment by eikek** [comment]
@kxbmap that looks nice! thank you for your very quick help!

**Comment by funkrusher** [comment]
does this still work? i can't seem to find the multidb example in the current master (0.5.1), thx!

**Comment by kxbmap** [comment]
Version 0.7.0 is released with multiple configurations support.

You can set seq of configurations to `jooqCodegen`:

```scala
jooqCodegenConfig := Seq[CodegenConfig](
  file("path/to/jooq-codegen-1.xml"),
  uri("classpath:path/to/jooq-codegen-2.xml"),
  <configuration>
    <!-- Your configurations -->
  </configuration>
)
```

And append configurations:

```scala
jooqCodegenConfig += file("jooq-codegen-3.xml")

jooqCodegenConfig ++= Seq(
  file("jooq-codegen-4.xml"),
  file("jooq-codegen-5.xml")
)
```
