### ISSUE TITLE
Add CodegenStrategy.Never

### ISSUE THREAD

**Issue by FredyH** [kxbmap/sbt-jooq#12]
There seems to be some buggy behaviour going on for me when I choose a target directory that isn't source managed, where it will  just run the codegen every single time I recompile even though the codegen strategy is set to IfAbsent.

I think it would be really cool if there was a codegen strategy that never generates code automatically, but rather the user would have to run the codegen manually using jooqCodegen in the sbt console.

This is especially useful in cases where you want to have the generated files as part of your project and everyone who checks it out does not require to have an already existing database to generate the jooq files.

**Comment by dpfeiffer** [comment]
As I need this as well for various reasons I can open a PR.

**Comment by dpfeiffer** [comment]
@kxbmap i just saw that this is already implemented and just needs to get released, is there a reason why the plugin has not been released with those changes?

**Comment by kxbmap** [comment]
Released plugin version 0.4.0 including this feature. Thank you.
