### ISSUE TITLE
disable code generation on compile

### ISSUE THREAD

**Issue by viggin543** [kxbmap/sbt-jooq#18]

**Comment by viggin543** [comment]
is there a way to disable code gen on compile task ?

currently im commenting out:
//jooqCodegenConfig := baseDirectory.value / "jooq-codegen.xml"
as a workaround

**Comment by kxbmap** [comment]
Thank you for using the plugin.

There are two ways to disable generation.

```scala
Compile / jooqCodegen / skip := true
```
This is the same as commenting out `jooqCodegenConfig`.
Disable both compile time generation and `jooqCodegen` task.

or
```scala
Compile / jooqCodegenStrategy := CodegenStrategy.Never
```
Disable compile time generation, but you can still execute generation using `jooqCodegen` manually.

**Comment by kxbmap** [comment]
Closing.
If you can't resolve the problem, please reopen this issue.
