### ISSUE TITLE
jooqCodegen on Java 11 leads to java.lang.module.FindException: Module java.xml.bind not found

### ISSUE THREAD

**Issue by HongyiFu** [kxbmap/sbt-jooq#19]
Hi, 

First of all, thank you for the great and comprehensive plugin!

Running `jooqCodegen` on Java 11 leads to the following stack trace. I don't understand why it is a `java.lang.module.FindException` instead of a `java.lang.ClassNotFoundException`. Does this mean the plugin is attempting to use module? 

```
[info] Running (fork) org.jooq.codegen.GenerationTool /var/folders/gp/6gtglsh166dbljpnnd9498l40000gn/T/jooq-codegen-16661343531966845890.xml
[info] Error occurred during initialization of boot layer
[info] java.lang.module.FindException: Module java.xml.bind not found
[error] Nonzero exit code returned from runner: 1
[error] (Jooq / run) Nonzero exit code returned from runner: 1
[error] Total time: 4 s, completed 11 Aug 2019, 1:47:59 AM
```

I have tried manually adding  `"org.glassfish.jaxb" % "jaxb-runtime" % "2.3.1" % Jooq` but to no avail, which is expected since it was not a `ClassNotFoundException`.

Looking at the source code at https://github.com/kxbmap/sbt-jooq/blob/44ba8f8075d812117ea351ea6bc438614788e6d1/src/main/scala/sbtjooq/codegen/JooqCodegenPlugin.scala#L63

you did not add `java.xml.bind` module for Java 11. Though you do not add module, but the resulting exception is a `java.lang.module.FindException`..

My setup:
- Java 11
- Scala 2.13.0
- sbt 1.2.8
- Jooq 3.11.11

**Comment by HongyiFu** [comment]
Upon closer inspection, it seems that the release 0.4.1 is not in-sync with master branch.

**Comment by badeball** [comment]
Neither does it work on 12 (OpenJDK).

**Comment by badeball** [comment]
Is there a workaround for using this with 11 / 12?

**Comment by HongyiFu** [comment]
If it's any help currently I am using my own seed/ template [here](https://github.com/HongyiFu/play-java-jooq-seed) (it's for Play Framework but should be easily customizable to suit other projects). 

Hopefully someone could fork this plugin and improve it, the master branch (which was not published) does seem to contain code that fixes for Java 11.

**Comment by kxbmap** [comment]
Sorry for the delay. Version 0.5.0 has been released.

You can use new version of codegen plugin with:
```scala
addSbtPlugin("com.github.kxbmap" % "sbt-jooq-codegen" % "0.5.0")
```
(not `sbt-jooq` but `sbt-jooq-codegen`)

There is many incompatible changes from 0.4.x.
I will update the README when I have time.

**Comment by larousso** [comment]
It works fine for me! Thanks !

**Comment by HongyiFu** [comment]
Nice!! Really appreciate it 👍 👍

**Comment by nerdydrew** [comment]
@kxbmap can you update the README to reflect these changes? This fixed my problem as well, but it took me a while to find. Thanks!
