### ISSUE TITLE
Is there a new release soon ? 

### ISSUE THREAD

**Issue by larousso** [kxbmap/sbt-jooq#20]
Hi, 

do you plan to release a new version soon with all the upgrades you've done on sbt / jooq ? 

Thanks for your job on this plugin!

**Comment by kxbmap** [comment]
Maybe this weekend.

**Comment by kxbmap** [comment]
Version 0.5.0 is released.
Please refer https://github.com/kxbmap/sbt-jooq/issues/19#issuecomment-559964489
