### ISSUE TITLE
scripted fails. tests use old version of flyway

### ISSUE THREAD

**Issue by benmccann** [kxbmap/sbt-jooq#23]
When I run `scripted` I get:

>[info] [warn] 
[info] [warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[info] [warn] 		org.flywaydb:flyway-sbt:4.2.0 (sbtVersion=1.0, scalaVersion=2.12)
[info] [warn] 
[info] [warn] 	Note: Unresolved dependencies path:
[info] [error] sbt.librarymanagement.ResolveException: Error downloading org.flywaydb:flyway-sbt;sbtVersion=1.0;scalaVersion=2.12:4.2.0
[info] [error]   Not found
[info] [error]   Not found
[info] [error]   not found: https://repo1.maven.org/maven2/org/flywaydb/flyway-sbt_2.12_1.0/4.2.0/flyway-sbt-4.2.0.pom
[info] [error]   not found: https://flywaydb.org/repo/org/flywaydb/flyway-sbt_2.12_1.0/4.2.0/flyway-sbt-4.2.0.pom
[info] [error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.flywaydb/flyway-sbt/scala_2.12/sbt_1.0/4.2.0/ivys/ivy.xml
[info] [error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.flywaydb/flyway-sbt/scala_2.12/sbt_1.0/4.2.0/ivys/ivy.xml

codegen/src/sbt-test/pending/integrate-flyway/project/plugins.sbt has `addSbtPlugin("org.flywaydb" % "flyway-sbt" % "4.2.0")`, which is a pretty old version. The latest would be `addSbtPlugin("io.github.davidmweber" % "flyway-sbt" % "6.2.3")`

**Comment by kxbmap** [comment]
Please use like `scripted jooq-codegen/*`.
I'm pending it until rewrite the test.
Or maybe I'll just delete the whole directory.

**Comment by kxbmap** [comment]
Fixed by 4598240444348d40513e49e2fb459470a5b90f42
