### ISSUE TITLE
Using the non open-source jooq jars

### ISSUE THREAD

**Issue by eikek** [kxbmap/sbt-jooq#7]
Hi,

I'm using the professional (or enterprise) version of jooq and I'm putting the jars in a `lib` folder so sbt can pick them up as unmanaged dependencies. Since this plugin adds a managed dependency automatically to the compile scope of the project, I have to remove it like this:

```
libraryDependencies ~= (_ filterNot (_.toString contains "jooq"))
```

Can we make this dependency optional? The default may still be as it is now, but it would be more convenient to remove it via a plugin setting. As an alternative, a workaround like above could be documented in the readme. What do you think?

**Comment by kxbmap** [comment]
Thank you for the feedback.
I think that add a new plugin setting is makes sense.

I have a question.
Is there the professional version of jooq-codegen/jooq-meta library? Or also putting them in a `lib` folder?
This plugin also adds these dependencies to the jooq scope to launch generation tool. If the answer is yes, they should be removed.

**Comment by eikek** [comment]
I'm not really sure…. If I download the professional version (the zip file) there are all the jars needed (maybe more):

- jooq-3.10.0.jar
- jooq-checker-3.10.0.jar
- jooq-codegen-3.10.0.jar
- jooq-codegen-maven-3.10.0.jar
- jooq-meta-3.10.0.jar
- jooq-meta-extensions-3.10.0.jar

I'm not sure, if some of them are the same as on maven central…. The dependency in the jooq scope doesn't hurt that much, because it only applies to the plugin, right? But, of course, it would be better to generate classes using the same jars as used in the project.

**Comment by eikek** [comment]
Thank you!! This was really quick.
